# Agent 配置文件

# API 配置
api:
  key: "sk-enter-your-apikey-here"
  base_url: "https://api.deepseek.com/v1"
  model: "deepseek-chat"

# 安全路径配置（AI在不允许危险操作的情况下可写入文件的路径）
# 若不改动则默认是AI的记忆目录、技巧目录、ai-programs目录。
safe_path: ["./memory","./skill","./ai-programs"]

# 控制台命令执行功能的超时时间，默认15分钟（900秒）
# 如果你需要让AI做极其耗费时间的任务（如编译项目、解压超大文件等）请适当调整该值
command_timeout: 900

# 各种工具向AI输出反馈的最大输出长度，默认10000字符
# 配置该选项可以防止神人AI执行某些遍历目录指令输出几百万字的数据把自己玩炸（
tool_output_length: 10000

# 端口配置，默认9600
server_port: 9600

# 温度，默认0.7
temperature: 0.7

# 是否自动打开浏览器，默认true
open_browser: true
